# Generated by Django 3.1.6 on 2022-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220209_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='total_uword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='total_word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='your_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
